Allow `clippy::double_must_use`.
Recently, I've been seeing the following lint on nightly:

error: this function has a `#[must_use]` attribute with no message,
but returns a type already considered as `#[must_use]`

Apprently, clippy recently changed the way it detects this condition:

https://github.com/rust-lang/rust-clippy/pull/16633

I've opened a bug at `async-trait`:

https://github.com/dtolnay/async-trait/issues/304

Since I use `async-trait` all over the place, I'm just going to allow
the lint crate-wide.